# Generated by Django 6.0 on 2025-12-17 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
