# Generated by Django 6.0 on 2025-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_certificate_qr_code_alter_certificate_certificate_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания курса'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Сертификат действителен'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/qr/', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала курса'),
        ),
    ]
